### ISSUE TITLE
Adding Questions to the Question Bank

### ISSUE THREAD

**Issue by Accuracy-exe** [acmpesuecc/Revisor#1]
This app's main purpose is for revision using micro tests... and tests can't be conducted without problems to solve.
The materials tab is a simple view to count total number of questions in the QB.json (Question Bank) file and a text input to accept more question objects (1 at max) to be added to the Question Bank
The current system takes one question as JSON object at a time.

Modify this to **accept and extract multiple questions at once**
Example - this is how the input to the text box should be : {question_object1}{question_object2}...
where question_object is the structure of the object defined in README.md

The Question counter must be updated accordingly

**Comment by gitsumchips** [comment]
Can I have this issue?

**Comment by Accuracy-exe** [comment]
!assign @gitsumchips

**Comment by Accuracy-exe** [comment]
!deassign

**Comment by Accuracy-exe** [comment]
Hey @gitsumchips , could you report your progress

**Comment by Sarah-Kazi** [comment]
please assign it to me

**Comment by Accuracy-exe** [comment]
!assign @Sarah-Kazi 50

**Comment by Peeyushhhhh** [comment]
can i get assigned please!!

**Comment by Accuracy-exe** [comment]
!assign @Peeyushhhh 60

**Comment by Accuracy-exe** [comment]
!assign @Peeyushhhhh

**Comment by suchiradi** [comment]
can you please assign me?

**Comment by gitsumchips** [comment]
Can I get this assigned to me?

**Comment by Rxnnie-08** [comment]
Can I get this assigned?

**Comment by Prabhanjan3247** [comment]
can I have this issue

**Comment by Accuracy-exe** [comment]
!assign @Prabhanjan3247

**Comment by Accuracy-exe** [comment]
!deassign

**Comment by gitsumchips** [comment]
Hello, can I get this assigned to me?

**Comment by Accuracy-exe** [comment]
!assign @gitsumchips

**Comment by Sami9692** [comment]
can u assign me???

**Comment by codebuddyjr** [comment]
assign me this pls

**Comment by Accuracy-exe** [comment]
This issue is solved
