### ISSUE TITLE
Personalization and Settings View

### ISSUE THREAD

**Issue by Accuracy-exe** [acmpesuecc/Revisor#4]
The Navigation Rail has the settings tab but it's not implemented yet
Add a personalization feature for changing accent color of the entire app which should be accessible via Settings tab

Hint: Flet's Docs ; )

**Comment by RecklessSoftwareGuy** [comment]
Please assign this issue to me

**Comment by Accuracy-exe** [comment]
!assign @RecklessSoftwareGuy 60

**Comment by ApoorvaSarganachari** [comment]
please assign

**Comment by Accuracy-exe** [comment]
Hey, Sorry, this issue has already been assigned to someone

**Comment by RecklessSoftwareGuy** [comment]
Please deassign

**Comment by mahika34** [comment]
can i be assigned

**Comment by velukutty2194** [comment]
please assign

**Comment by mahika34** [comment]
can i be assigned?

**Comment by Accuracy-exe** [comment]
!deassign

**Comment by Accuracy-exe** [comment]
Solved by @mahika34
